Areas/Admin/Controllers/ProjectItemsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnlinePanelForProjectsControl.Controllers;
using OnlinePanelForProjectsControl.Domain;
using OnlinePanelForProjectsControl.Domain.Entities;
using OnlinePanelForProjectsControl.Models.ViewComponents;
using OnlinePanelForProjectsControl.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace OnlinePanelForProjectsControl.Areas.Admin.Controllers
{
    [Area("Admin")]
	public class ProjectItemsController : Controller
	{
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public ProjectItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new ProjectItem() { DateOfStart = DateTime.UtcNow, PlannedDateOfEnd=DateTime.UtcNow} : dataManager.ProjectItems.GetProjectItemById(id);
            if(entity.ProjectTasks == null)
			{
                entity.ProjectTasks = new List<ProjectTask>();
                entity.ProjectTasks = dataManager.ProjectTasks.GetAllAsignedTasks(entity.Id).ToList();
            }
            return View(entity);
        }

        [HttpPost]
        public IActionResult AddDeveloperToProject(Guid projectId, string devId)
        {
            var entity = dataManager.ProjectItems.GetProjectItemById(projectId);
            var dev = dataManager.IdentityUsers.GetUserById(devId);

            dataManager.ProjectDevs.SaveProjectDev(new ProjectDevs { Id = new Guid(), DevId = devId, DeveloperItem = dataManager.IdentityUsers.GetUserById(devId),
                ProjectId = projectId, Project = dataManager.ProjectItems.GetProjectItemById(projectId) });

            return RedirectToAction(nameof(ProjectsController.Index), nameof(ProjectsController).CutController(), new { area = "default" ,id=projectId});
		}

        [HttpPost]
        public IActionResult Edit(ProjectItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.ProjectItems.SaveProjectItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.ProjectItems.DeleteProjectItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

Controllers/ProjectTaskController.cs
using Microsoft.AspNetCore.Mvc;
using OnlinePanelForProjectsControl.Domain;
using OnlinePanelForProjectsControl.Domain.Entities;
using OnlinePanelForProjectsControl.Models;
using OnlinePanelForProjectsControl.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlinePanelForProjectsControl.Controllers
{
	public class ProjectTaskController : Controller
	{
		private readonly DataManager dataManager;
		public ProjectTaskController(DataManager dataManager)
		{
			this.dataManager = dataManager;
		}
        public IActionResult Index(Guid id)
        {
            return View(dataManager.ProjectTasks.GetProjectTaskById(id));
        }

		public IActionResult Edit(Guid id, Guid projectId)
		{
			ProjectTask task = dataManager.ProjectTasks.GetProjectTaskById(id);
			ProjectTaskViewModel model = new ProjectTaskViewModel() { ProjectTaskReference = task };
			return View(model);
		}

		[HttpPost]
		public IActionResult Edit(ProjectTaskViewModel model)
		{
			if (ModelState.IsValid)
			{
				ProjectTask task = dataManager.ProjectTasks.GetProjectTaskById(model.ProjectTaskReference.TaskID);
				task.SpendedTime = model.ProjectTaskReference.SpendedTime;
				task.isFinished = model.ProjectTaskReference.isFinished;
				task.TaskDescription = model.ProjectTaskReference.TaskDescription;

				dataManager.ProjectTasks.SaveProjectTask(task);
				return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
			}
			return View(model);
		}
	}
}

Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlinePanelForProjectsControl.Domain;
using OnlinePanelForProjectsControl.Domain.Entities;
using OnlinePanelForProjectsControl.Models.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlinePanelForProjectsControl.Controllers
{
	public class ProjectsController : Controller
	{
        private readonly DataManager dataManager;

        public ProjectsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                ProjectItemViewModel model = new ProjectItemViewModel();
                model.ProjectItem = dataManager.ProjectItems.GetProjectItemById(id);
                if(model.ProjectItem.ProjectTasks == null)
				{
                    model.ProjectItem.ProjectTasks = dataManager.ProjectTasks.GetAllAsignedTasks(model.ProjectItem.Id).ToList();
				}
                if(model.ProjectItem.Devs == null)
				{
                    model.ProjectItem.Devs = dataManager.ProjectDevs.GetAllProjectDevs(model.ProjectItem.Id).ToList();
                    model.AssignedDevs = dataManager.ProjectDevs.GetAllDevelopersFromProject(model.ProjectItem.Id).ToList();
				}
                List<Developer> selList = dataManager.IdentityUsers.GetAllUsers().ToList();
                for(int i = 0; i< model.AssignedDevs.Count; i++)
				{
                    selList.Remove(dataManager.IdentityUsers.GetUserById(model.AssignedDevs[i].Id));
				}
                model.NewDev = new SelectList(selList, "Id","UserName");
                return View("Show", model);
            }
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageProjects");
            return View(dataManager.ProjectItems.GetProjectItems());
        }
    }
}

Controllers/ReportsController.cs
using iText.Kernel.Colors;
using iText.Kernel.Geom;
using iText.Kernel.Pdf;
using iText.Kernel.Pdf.Canvas.Draw;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using Microsoft.AspNetCore.Mvc;
using OnlinePanelForProjectsControl.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Threading.Tasks;
using iText.IO.Font.Constants;
using iText.Kernel.Font;
using Microsoft.AspNetCore.Hosting;
using OnlinePanelForProjectsControl.Domain;
using OnlinePanelForProjectsControl.Domain.Entities;

namespace OnlinePanelForProjectsControl.Areas.Controllers
{
	public class ReportsController : Controller
	{
		private readonly DataManager dataManager;
		private readonly IWebHostEnvironment hostingEnvironment;
		public ReportsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
		{
			this.dataManager = dataManager;
			this.hostingEnvironment = hostingEnvironment;
		}

		public async Task<IActionResult> Index(Guid id)
		{
			string directory = Directory.GetCurrentDirectory().ToString();
			PdfFont font = PdfFontFactory.CreateFont(directory + "/wwwroot/fonts/times-new-roman-cyr.ttf");
			MemoryStream ms = new MemoryStream();
			PdfWriter writer = new PdfWriter(ms);
			PdfDocument pdfDocument = new PdfDocument(writer);
			Document document = new Document(pdfDocument, PageSize.A4.Rotate());
			writer.SetCloseStream(false);
			document.SetFont(font);
			ProjectItem projectItem = dataManager.ProjectItems.GetProjectItemById(id);

			List<ProjectTask> projectTasks = dataManager.ProjectTasks.GetAllAsignedTasks(projectItem.Id).ToList();
			double done = 0;
			int undone = 0;
			string percent;
			for (int i = 0; i < projectTasks.Count; i++)
			{
				if (projectTasks[i].isFinished) done++;
				else undone++;
			}
			if (undone == 0)
			{
				percent = "100%";
			}
			else
			{
				percent = Math.Round(((done / projectTasks.Count) * 100), 2).ToString() + "%";
			}
			string status;
			if (undone > 0 & projectTasks.Count != 0)
			{
				status = "В розробці";
			}
			else
			{
				status = "Завершений";
			}
			document.Add(new Paragraph(projectItem.Title).SetTextAlignment(TextAlignment.CENTER));

			Table table = new Table(4, false);

			Cell cellStatus = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.LIGHT_GRAY)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph("Статус проекта"));
			Cell cellFinishPercent = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.LIGHT_GRAY)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph("Процент готовності проекту"));
			Cell cellMissedDays = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.LIGHT_GRAY)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph("Відхилення від назначеної дати"));
			Cell cellUsedHoursOfWork = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.LIGHT_GRAY)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph("Кількість витраченого часу"));
			Cell CellDoneTasks = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.WHITE)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph(status));
			Cell CellOfFinishedWork = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.WHITE)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph(percent));
			string missedDateMessage;
			if (projectItem.PlannedDateOfEnd > DateTime.UtcNow)
			{
				missedDateMessage = "Залишилось: " + (projectItem.PlannedDateOfEnd - DateTime.UtcNow).Days.ToString() + " дні"; ;
			}
			else
			{
				missedDateMessage = "До кінця сроку: " + (projectItem.PlannedDateOfEnd - DateTime.UtcNow).Days.ToString().Trim('-') + "Дні";
			}
			Cell CellMissedEndTime = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.WHITE)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph(missedDateMessage));
			int estimatedTime = 0;
			int spendedTime = 0;
			for (int i = 0; i < projectTasks.Count; i++)
			{
				estimatedTime += projectTasks[i].EstimatedTime;
				spendedTime += projectTasks[i].SpendedTime;
			}

			Cell CellSpendedTime = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.WHITE)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph("Витрачено часу: " + spendedTime + "/" + estimatedTime + " годин"));


			table.AddCell(cellStatus);
			table.AddCell(cellFinishPercent);
			table.AddCell(cellMissedDays);
			table.AddCell(cellUsedHoursOfWork);
			table.AddCell(CellDoneTasks);
			table.AddCell(CellOfFinishedWork);
			table.AddCell(CellMissedEndTime);
			table.AddCell(CellSpendedTime);

			Table TaskTable = new Table(4, false);
			table.UseAllAvailableWidth();
			document.Add(table);
			document.Add(new Paragraph());
			document.Add(new Paragraph("Задачі проекту").SetTextAlignment(TextAlignment.CENTER));
			Cell cellTaskNameHead = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.LIGHT_GRAY)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph("Назва задачі"));
			Cell cellTaskTimeHead = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.LIGHT_GRAY)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph("Витрачений/Запланований час"));
			Cell cellTaskStatusHead = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.LIGHT_GRAY)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph("Статус задачі"));
			Cell cellDeveloperHead = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.LIGHT_GRAY)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph("Розробник"));

			TaskTable.AddCell(cellTaskNameHead);
			TaskTable.AddCell(cellTaskTimeHead);
			TaskTable.AddCell(cellTaskStatusHead);
			TaskTable.AddCell(cellDeveloperHead);

			foreach (var task in projectTasks)
			{
				Cell cellTaskName = new Cell(1, 1)
					.SetBackgroundColor(ColorConstants.WHITE)
					.SetTextAlignment(TextAlignment.CENTER)
					.Add(new Paragraph(task.TaskName));
				Cell cellTaskTime = new Cell(1, 1)
					.SetBackgroundColor(ColorConstants.WHITE)
					.SetTextAlignment(TextAlignment.CENTER)
					.Add(new Paragraph(task.SpendedTime + "/" + task.EstimatedTime));
				string taskstatus;
				if (task.isFinished) taskstatus = "Виконано";
				else taskstatus = "В розробці";
				Cell cellTaskStatus = new Cell(1, 1)
					.SetBackgroundColor(ColorConstants.WHITE)
					.SetTextAlignment(TextAlignment.CENTER)
					.Add(new Paragraph(taskstatus));
				Cell cellDeveloper = new Cell(1, 1)
					.SetBackgroundColor(ColorConstants.WHITE)
					.SetTextAlignment(TextAlignment.CENTER)
					.Add(new Paragraph(dataManager.IdentityUsers.GetUserById(task.DeveloperId).UserName));

				TaskTable.AddCell(cellTaskName);
				TaskTable.AddCell(cellTaskTime);
				TaskTable.AddCell(cellTaskStatus);
				TaskTable.AddCell(cellDeveloper);
			}
			TaskTable.UseAllAvailableWidth();
			document.Add(new Paragraph());
			document.Add(TaskTable);

			document.Add(new Paragraph("Продуктивність розробників").SetTextAlignment(TextAlignment.CENTER));

			Table devTable = new Table(4, false);

			Cell cellDevNameTitle = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.LIGHT_GRAY)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph("Розробник"));
			Cell cellWorkEficiencyTitle = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.LIGHT_GRAY)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph("Відсоток виконаних задач"));
			Cell cellAssignedTasks = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.LIGHT_GRAY)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph("Кількість назначених задач"));
			Cell cellSpendedTime = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.LIGHT_GRAY)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph("Затрачений час розробника"));

			devTable.AddCell(cellDevNameTitle);
			devTable.AddCell(cellWorkEficiencyTitle);
			devTable.AddCell(cellAssignedTasks);
			devTable.AddCell(cellSpendedTime);

			List<Developer> Devs = dataManager.ProjectDevs.GetAllDevelopersFromProject(projectItem.Id).ToList();

			foreach (var dev in Devs)
			{
				Cell cellDevName = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.WHITE)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph(dev.UserName));
				List<ProjectTask> assignedTask = projectTasks.Where(x => x.DeveloperId == dev.Id).ToList();
				List<ProjectTask> donedTask = assignedTask.Where(x => x.isFinished == true).ToList();
				int devSpendedTime = 0;
				string doneWork;
				for (int i = 0; i < assignedTask.Count; i++)
				{
					devSpendedTime += assignedTask[i].SpendedTime;
				}
				double percentOfDoneWork = 0;

				if (donedTask.Count == 0)
				{
					percentOfDoneWork = 0;
				}
				else
				{
					percentOfDoneWork = Math.Round(((double)donedTask.Count / (double)assignedTask.Count) * 100, 2);
				}
				doneWork = percentOfDoneWork.ToString().Trim('-') + "%";
				Cell cellDevEfficiency = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.WHITE)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph(doneWork));
				Cell cellDevAssignedTasks = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.WHITE)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph(assignedTask.Count.ToString()));
				Cell cellDevSpendedTime = new Cell(1, 1)
				.SetBackgroundColor(ColorConstants.WHITE)
				.SetTextAlignment(TextAlignment.CENTER)
				.Add(new Paragraph(devSpendedTime.ToString()));


				devTable.AddCell(cellDevName);
				devTable.AddCell(cellDevEfficiency);
				devTable.AddCell(cellDevAssignedTasks);
				devTable.AddCell(cellDevSpendedTime);
			}
			devTable.UseAllAvailableWidth();
			document.Add(devTable);

			document.Close();
			byte[] byteInfo = ms.ToArray();
			ms.Write(byteInfo, 0, byteInfo.Length);
			ms.Position = 0;
			FileStreamResult fileStreamResult = new FileStreamResult(ms, "application/pdf");
			//fileStreamResult.FileDownloadName = "NorthwindProducts.pdf";

			return fileStreamResult;
		}
	}
}

Views/Projects/Index.cshtml
@model IQueryable<ProjectItem>
@{
    string strTitle = "Проекти";
    ViewBag.Title = strTitle;
}

<div>
    <h2>@strTitle</h2>
    <div>
    @if (Model.Any())
    {
        <ul class="big-image-list">
            @foreach (ProjectItem entity in Model)
            {
                <a asp-area="" asp-controller="Projects" asp-action="Index" asp-route-id="@entity.Id">
                <li>
                    @if (@entity.TitleImagePath != null)
                    {
                        <img width="200" src="~/images/@entity.TitleImagePath" alt="" class="left" />
                    }
                    <h3>@entity.Title</h3>
                    <p>@entity.Subtitle</p>
                </li>
                </a>
                <hr>
            }
        </ul>
    }
    </div>
</div>

Views/Projects/Show.cshtml
@model ProjectItemViewModel
@{
    ViewBag.Title = Model.ProjectItem.MetaTitle;
    ViewBag.Description = Model.ProjectItem.MetaDescription;
    ViewBag.Keywords = Model.ProjectItem.MetaKeywords;
}
<div>
    <h2>
        @Model.ProjectItem.Title
    </h2>
    <h3>
        @Model.ProjectItem.Subtitle
    </h3>
    <div>
        <img class="big-image-list" src="~/images/@Model.ProjectItem.TitleImagePath" />
    </div>
    <div>
        <h3 style="text-size-adjust:150%;">Опис проекту:</h3>
        @Html.Raw(Model.ProjectItem.Text)
    </div>
    <table style="margin-top:20px; ">
        <thead>
        <th>
            <label>Назва задачі</label>
        </th>
        <th>
            <label>Виділений час на задачу<label>
        </th>
        <th>
            <label">Затрачений час на задачу</label">
        </th>
        <th>
            <label>Статус задачі</label>
        </th>
        <th>
            <label>Розробник</label>
        </th>
        </thead>

        @for (int i = 0; i < Model.ProjectItem.ProjectTasks.Count; i++)
        {

            <tr>
                <td>
                    <label>@Model.ProjectItem.ProjectTasks[i].TaskName</label>
                </td>
                <td>
                    <input readonly asp-for="@Model.ProjectItem.ProjectTasks[i].EstimatedTime" />
                </td>
                <td>
                    <input readonly asp-for="@Model.ProjectItem.ProjectTasks[i].SpendedTime" />
                </td>
                <td>
                    <input disabled type="checkbox" asp-for="@Model.ProjectItem.ProjectTasks[i].isFinished" />
                </td>
                <td>
                    @if (Model.ProjectItem.ProjectTasks[i].Developer != null)
                    {
                        <label>@Model.ProjectItem.ProjectTasks[i].Developer.UserName</label>
                    }
                    else
                    {
                        <label>Розробник не назначений</label>
                    }
                </td>
                @if (User.IsInRole("admin"))
                {
                    <td>
                        <a asp-area="Admin" asp-controller="ProjectTasks" asp-action="Edit" asp-route-id="@Model.ProjectItem.ProjectTasks[i].TaskID" asp-route-projectId="@Model.ProjectItem.Id">Редагувати</a>
                        <a asp-area="Admin" asp-controller="ProjectTasks" asp-action="Delete" asp-route-id="@Model.ProjectItem.ProjectTasks[i].TaskID">Видалити</a>
                    </td>
                }
                else
                {
                    <td>
                        <a asp-area="" asp-controller="ProjectTask" asp-action="Edit" asp-route-id="@Model.ProjectItem.ProjectTasks[i].TaskID" asp-route-projectId="@Model.ProjectItem.Id">Редагувати</a>
                    </td>
                }

            </tr>

        }
    </table>
    @if (User.IsInRole("admin"))
    {
        <a asp-area="Admin" asp-controller="ProjectTasks" asp-action="Edit" asp-route-projectId="@Model.ProjectItem.Id">Додати задачу</a>
        <br>
    }
    <h3 style="margin-top:10px; margin-bottom:10px">Назначені розробники:</h3>
    @for (int i = 0; i < Model.AssignedDevs.Count; i++)
    {
        <label>@Model.AssignedDevs[i].UserName, </label>
    }
    @if (User.IsInRole("admin") & Model.NewDev.Count() > 0)
    {
        <form style="margin-top:-20px" asp-area="Admin" asp-controller="ProjectItems" asp-action="AddDeveloperToProject" asp-route-projectId="@Model.ProjectItem.Id" method="post">
            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <select name="devId" asp-items="Model.NewDev"></select>
            </div>
            <input type="submit" value="Додати розробника" />
        </form>
    }
    <br>
    @if (User.IsInRole("admin"))
    {
        <a asp-area="Admin" asp-controller="Reports" asp-action="Index" asp-route-id="@Model.ProjectItem.Id"><h3>Отримати звіт по проекту в Pdf форматі</h3></a>
    }
    else
    {
        <a asp-area="" asp-controller="Reports" asp-action="Index" asp-route-id="@Model.ProjectItem.Id">Отримати звіт по проекту в Pdf форматі</a>
    }
</div>